services:
  api:
    image: tuhinsu/node:lts
    container_name: api.${PROJECT_NAME}.${PROJECT_DOMAIN}
    volumes:
      - .:/app
    user: vscode
    command: bash start.sh
    restart: unless-stopped
