services:
  api:
    image: tuhinsu/node:lts
    container_name: api.${PROJECT_NAME}.${PROJECT_DOMAIN}
    volumes:
      - .:/app
      - ./dotfiles:/home/vscode
    environment:
      - PRODUCTION=${PRODUCTION}
      - VERSION=${VERSION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - USE_REDIS=${USE_REDIS}
      - SECRET_KEY=${SECRET_KEY}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
    user: vscode
    command: bash start.sh
    restart: unless-stopped

  redis:
    image: redis
    container_name: redis.${PROJECT_NAME}.${PROJECT_DOMAIN}
    volumes:
      - ./db/redis:/data
    restart: unless-stopped
  
  sqlpad:
    image: sqlpad/sqlpad:latest
    container_name: sqlpad.${PROJECT_NAME}.${PROJECT_DOMAIN}
    environment:
      - SQLPAD_ADMIN=test@email.com
      - SQLPAD_ADMIN_PASSWORD=admin123
      - SQLPAD_APP_LOG_LEVEL=debug
      - SQLPAD_WEBHOOK_ENABLED=false
      - SQLPAD_DISABLE_TELEMETRY=true
    restart: unless-stopped
