services:
  api:
    image: tuhinsu/node:lts
    container_name: api.${PROJECT_NAME}.${PROJECT_DOMAIN}
    volumes:
      - .:/app
      - dotfiles:/home/vscode
    environment:
      - PRODUCTION=${PRODUCTION}
      - PORT=80
      - VERSION=${VERSION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - USE_REDIS=${USE_REDIS}
      - SECRET_KEY=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
    user: root
    command: bash start.sh
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.timt.in`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=letsencrypt"
      - "traefik.http.services.api.loadbalancer.server.port=80
