
services:
  api:
    image: tuhinsu/node:lts
    container_name: api.${PROJECT_DOMAIN}
    volumes:
      - .:/app
      - dotfiles:/home/vscode
    environment:
      - PRODUCTION=${PRODUCTION}
      - VERSION=${VERSION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - USE_REDIS=${USE_REDIS}
      - SECRET_KEY=${SECRET_KEY}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
    user: root
    command: bash start.sh
    restart: unless-stopped
    networks:
      - loop
      - common

  redis:
    image: redis
    container_name: redis.${PROJECT_DOMAIN}
    volumes:
      - ./db/redis:/data
    restart: unless-stopped
    networks:
      - loop

volumes:
  dotfiles:
    external: true

networks:
  loop:
    driver: bridge
  common:
    external: true
